# Generated by Django 5.2.13 on 2026-04-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('base_url', models.CharField(blank=True, default='', max_length=500, verbose_name='测试目标 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('generate', '生成用例'), ('analyze', '分析结果'), ('chat', '自由对话')], max_length=20, verbose_name='对话类型')),
                ('user_message', models.TextField(verbose_name='用户消息')),
                ('ai_response', models.TextField(verbose_name='AI 回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='core.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'AI 对话',
                'verbose_name_plural': 'AI 对话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='用例描述')),
                ('steps', models.TextField(help_text='自然语言描述的测试步骤', verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '就绪'), ('running', '运行中'), ('passed', '通过'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='AI 生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('passed', '通过'), ('failed', '失败'), ('error', '异常')], default='pending', max_length=20, verbose_name='状态')),
                ('log', models.TextField(blank=True, default='', verbose_name='执行日志')),
                ('screenshot_path', models.CharField(blank=True, default='', max_length=500, verbose_name='截图路径')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='耗时(秒)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.project', verbose_name='所属项目')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.testcase', verbose_name='关联用例')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
