# Generated by Django 5.2.13 on 2026-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_token',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='GitHub Token'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='GitHub 地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='local_repo_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='本地仓库路径'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_password',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='仓库凭证/密码'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Git 仓库地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_username',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='仓库账号'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='markdown_content',
            field=models.TextField(blank=True, default='', verbose_name='Markdown 内容'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='priority',
            field=models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2')], default='', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='测试类型'),
        ),
    ]
