# Generated by Django 5.2.13 on 2026-04-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_github_token_project_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='AI 模型'),
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='execution_mode',
            field=models.CharField(choices=[('script', '脚本模式'), ('agent', 'Agent 模式')], default='script', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='tool_calls_count',
            field=models.IntegerField(default=0, verbose_name='工具调用次数'),
        ),
    ]
