# Generated by Django 5.2.13 on 2026-04-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_agent_fields_to_executionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list, help_text='Agent 多轮对话的消息记录', verbose_name='对话历史'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_by',
            field=models.CharField(choices=[('manual', '手动创建'), ('claude_cli', 'Claude CLI'), ('agent', 'Agent 生成')], default='manual', max_length=20, verbose_name='创建方式'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='target_page_or_api',
            field=models.CharField(blank=True, default='', help_text='具体的页面路径或 API 端点', max_length=500, verbose_name='测试目标页面/API'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本号'),
        ),
    ]
