# Generated by Django 5.2.13 on 2026-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_testcase_agent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='agent_response',
            field=models.JSONField(blank=True, default=dict, help_text='Agent 执行的完整原始响应数据', verbose_name='Agent 原始响应'),
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='screenshots',
            field=models.JSONField(blank=True, default=list, help_text='Agent 执行过程中的截图路径列表', verbose_name='截图列表'),
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='step_logs',
            field=models.JSONField(blank=True, default=list, help_text='结构化的逐步执行日志', verbose_name='逐步日志'),
        ),
    ]
