# Generated by Django 5.2.13 on 2026-04-30 01:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_execution_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=core.models._screenshot_upload_path, verbose_name='截图文件')),
                ('step_num', models.IntegerField(blank=True, null=True, verbose_name='步骤序号')),
                ('action', models.CharField(blank=True, default='', max_length=200, verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_records', to='core.executionrecord', verbose_name='关联执行记录')),
            ],
            options={
                'verbose_name': '截图',
                'verbose_name_plural': '截图',
                'ordering': ['step_num'],
            },
        ),
    ]
