# Generated by Django 6.0.4 on 2026-04-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_screenshot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='auto_captured',
            field=models.BooleanField(default=False, help_text='是否为定时自动截图（非工具触发）', verbose_name='自动截图'),
        ),
    ]
