# Generated by Django 5.2.13 on 2026-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_captured_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='replay_script',
            field=models.JSONField(blank=True, default=None, help_text='从 Agent 执行生成的结构化可编辑 Playwright 脚本', null=True, verbose_name='可回放脚本'),
        ),
        migrations.AlterField(
            model_name='executionrecord',
            name='execution_mode',
            field=models.CharField(choices=[('script', '脚本模式'), ('agent', 'Agent 模式'), ('replay', '脚本回放')], default='script', max_length=20, verbose_name='执行模式'),
        ),
    ]
