# Generated by Django 5.2.13 on 2026-04-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_replay_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionrecord',
            name='source_execution',
            field=models.ForeignKey(blank=True, help_text='回放执行时指向源脚本所在的执行记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replay_runs', to='core.executionrecord', verbose_name='来源执行记录'),
        ),
    ]
