# Generated by Django 5.2.13 on 2026-05-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_source_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreconditionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('steps', models.TextField(help_text='自然语言描述的前置步骤', verbose_name='前置步骤')),
                ('markdown_content', models.TextField(blank=True, default='', help_text='完整的 Markdown 格式前置条件文档', verbose_name='Markdown 内容')),
                ('is_default', models.BooleanField(default=False, verbose_name='系统内置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '前置条件模板',
                'verbose_name_plural': '前置条件模板',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('analyzing', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='分析状态')),
                ('local_repo_path', models.CharField(blank=True, default='', max_length=500, verbose_name='本地仓库路径')),
                ('discovered_items', models.JSONField(blank=True, default=list, help_text='分析发现的页面和 API 列表，结构为 [{type, path, name, method, description, source_file}]', verbose_name='发现列表')),
                ('analysis_log', models.TextField(blank=True, default='', verbose_name='分析日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_analyses', to='core.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '仓库分析',
                'verbose_name_plural': '仓库分析',
                'ordering': ['-created_at'],
            },
        ),
    ]
