# Generated by Django 5.2.13 on 2026-05-01 05:38

from django.db import migrations


def create_default_precondition_templates(apps, schema_editor):
    PreconditionTemplate = apps.get_model('core', 'PreconditionTemplate')
    templates = [
        {
            'name': 'SSO 统一登录',
            'description': '通过 SSO 单点登录系统完成身份认证，适用于需要登录后操作的场景',
            'steps': '1. 打开应用登录页\n2. 点击 SSO 登录按钮跳转到统一认证页面\n3. 输入 SSO 账号和密码\n4. 完成验证码验证（如需）\n5. 点击登录按钮\n6. 等待页面跳转回应用并确认登录成功',
            'markdown_content': '## 前置条件：SSO 统一登录\n\n### 环境准备\n- SSO 测试账号已创建\n- 应用已接入 SSO 系统\n\n### 登录步骤\n1. 打开目标应用 URL\n2. 点击「SSO 登录」按钮\n3. 在统一认证页面输入测试账号和密码\n4. 如有验证码，输入对应验证码\n5. 点击「登录」\n6. 确认跳转回应用且显示已登录状态\n\n### 预期\n- 登录成功后页面显示用户信息\n- 能正常访问需登录的功能',
            'is_default': True,
        },
        {
            'name': '管理员登录',
            'description': '使用管理员账号登录系统，适用于需要管理员权限的测试场景',
            'steps': '1. 打开系统登录页\n2. 输入管理员账号\n3. 输入管理员密码\n4. 点击登录按钮\n5. 确认登录成功且拥有管理员权限',
            'markdown_content': '## 前置条件：管理员登录\n\n### 环境准备\n- 管理员测试账号已创建\n- 账号拥有系统管理员角色\n\n### 登录步骤\n1. 打开系统登录页面\n2. 在账号输入框输入管理员账号\n3. 在密码输入框输入管理员密码\n4. 点击「登录」按钮\n5. 等待页面加载完成\n\n### 预期\n- 登录成功跳转至管理后台首页\n- 页面显示管理员菜单和功能入口\n- 用户角色标识为「管理员」',
            'is_default': True,
        },
        {
            'name': '普通用户登录',
            'description': '使用普通用户账号登录系统，适用于常规功能测试场景',
            'steps': '1. 打开系统登录页\n2. 输入普通用户账号\n3. 输入用户密码\n4. 点击登录按钮\n5. 确认登录成功',
            'markdown_content': '## 前置条件：普通用户登录\n\n### 环境准备\n- 普通用户测试账号已创建\n- 账号状态正常（未禁用）\n\n### 登录步骤\n1. 打开系统登录页面\n2. 输入普通用户账号\n3. 输入对应用户密码\n4. 点击「登录」按钮\n5. 等待页面加载完成\n\n### 预期\n- 登录成功跳转至系统首页\n- 页面显示普通用户可访问的功能菜单\n- 用户角色标识正确',
            'is_default': True,
        },
    ]
    for tpl_data in templates:
        PreconditionTemplate.objects.get_or_create(
            name=tpl_data['name'],
            defaults=tpl_data,
        )


def reverse_default_precondition_templates(apps, schema_editor):
    PreconditionTemplate = apps.get_model('core', 'PreconditionTemplate')
    PreconditionTemplate.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_repo_analysis_and_precondition_template'),
    ]

    operations = [
        migrations.RunPython(
            create_default_precondition_templates,
            reverse_default_precondition_templates,
        ),
    ]
