# Generated by Django 5.2.13 on 2026-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_default_precondition_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['feature_group', 'sort_order', '-updated_at'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AddField(
            model_name='testcase',
            name='feature_group',
            field=models.CharField(blank=True, default='', help_text='用例所属功能模块，如「用户登录」「订单管理」', max_length=200, verbose_name='功能点'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='组内执行顺序，数字越小越先执行', verbose_name='排序序号'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['feature_group', 'sort_order'], name='idx_tc_group_order'),
        ),
    ]
