# Generated by Django 5.2.13 on 2026-05-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_feature_group_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='默认继承用例名称', max_length=300, verbose_name='脚本名称')),
                ('feature_group', models.CharField(blank=True, default='', help_text='脚本所属功能模块', max_length=200, verbose_name='功能分组')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序序号')),
                ('script_data', models.JSONField(default=dict, help_text='结构化脚本内容，含 parameters 和 steps', verbose_name='脚本内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.project', verbose_name='所属项目')),
                ('source_execution', models.ForeignKey(blank=True, help_text='生成此脚本的 Agent 执行记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_scripts', to='core.executionrecord', verbose_name='来源执行记录')),
                ('testcase', models.ForeignKey(blank=True, help_text='可选，关联被脚本化的原始测试用例', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='core.testcase', verbose_name='关联用例')),
            ],
            options={
                'verbose_name': '测试脚本',
                'verbose_name_plural': '测试脚本',
                'ordering': ['feature_group', 'sort_order', '-updated_at'],
            },
        ),
    ]
