# Generated by Django 5.2.13 on 2026-05-01 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_script_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='方案名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='方案描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('api_token', models.UUIDField(default=uuid.uuid4, help_text='CI/CD 调用凭证，通过 X-Plan-Token header 传递', unique=True, verbose_name='API Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='core.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '用例方案',
                'verbose_name_plural': '用例方案',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('script', '脚本'), ('feature_group', '功能分组')], help_text='script: 单个脚本, feature_group: 执行该分组下所有活跃脚本', max_length=20, verbose_name='子项类型')),
                ('feature_group_name', models.CharField(blank=True, default='', help_text='item_type=feature_group 时要执行的分组名称', max_length=200, verbose_name='功能分组名称')),
                ('sort_order', models.IntegerField(default=0, help_text='执行顺序，数字越小越先执行', verbose_name='排序序号')),
                ('script', models.ForeignKey(blank=True, help_text='item_type=script 时关联的脚本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='core.script', verbose_name='关联脚本')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.testplan', verbose_name='所属方案')),
            ],
            options={
                'verbose_name': '方案子项',
                'verbose_name_plural': '方案子项',
                'ordering': ['sort_order'],
            },
        ),
    ]
