# Generated by Django 5.2.13 on 2026-05-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_testplan_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('error', '异常')], default='pending', max_length=20, verbose_name='状态')),
                ('trigger_source', models.CharField(choices=[('manual', '手动触发'), ('api', 'API 调用')], default='manual', max_length=20, verbose_name='触发来源')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='包含 total/passed/failed/error/skipped 计数', verbose_name='执行摘要')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_executions', to='core.project', verbose_name='所属项目')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.testplan', verbose_name='关联方案')),
            ],
            options={
                'verbose_name': '方案执行记录',
                'verbose_name_plural': '方案执行记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='executionrecord',
            name='plan_execution',
            field=models.ForeignKey(blank=True, help_text='该记录属于哪个方案执行（独立执行时为空）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='core.planexecution', verbose_name='所属方案执行'),
        ),
    ]
