# Generated by Django 5.2.13 on 2026-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_migrate_replay_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='generation_draft',
            field=models.JSONField(blank=True, default=dict, help_text='用例批量生成过程中的临时草稿数据，用于页面刷新后恢复状态', verbose_name='生成草稿'),
        ),
    ]
