# Generated by Django 5.2.13 on 2026-05-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_generation_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoanalysis',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近心跳时间'),
        ),
        migrations.AddField(
            model_name='repoanalysis',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始分析时间'),
        ),
    ]
