# Generated by Django 5.2.13 on 2026-05-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_repoanalysis_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplanitem',
            name='testcase',
            field=models.ForeignKey(blank=True, help_text='item_type=agent_testcase 时关联的测试用例', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_items', to='core.testcase', verbose_name='关联用例'),
        ),
        migrations.AlterField(
            model_name='testplanitem',
            name='item_type',
            field=models.CharField(choices=[('script', '脚本'), ('feature_group', '功能分组'), ('agent_testcase', 'Agent用例')], help_text='script: 单个脚本, feature_group: 执行该分组下所有活跃脚本, agent_testcase: Agent模式执行用例', max_length=20, verbose_name='子项类型'),
        ),
    ]
