# Generated by Django 5.2.13 on 2026-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_testcase_to_plan_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_context',
            field=models.JSONField(blank=True, default=dict, help_text='代码分析提取的丰富上下文信息，用于 Agent 执行时直接引用。页面类型: {context_type, path, source_file, elements: [{selector, type, label}]}。API类型: {context_type, path, method, source_file, params: [...], response_fields: [...]}', verbose_name='测试上下文'),
        ),
        migrations.AlterField(
            model_name='repoanalysis',
            name='discovered_items',
            field=models.JSONField(blank=True, default=list, help_text='分析发现的页面和 API 列表。页面: [{type:"page", path, name, description, source_file, elements: [{selector, type, label, description}]}]。API: [{type:"api", path, method, name, description, source_file, params: [{name, in, type, required, description}], response_fields: [{name, type, description}]}]', verbose_name='发现列表'),
        ),
    ]
